Oauth
TuringGameNight/Front-End pull request #34
Opened 2021-01-12 04:02 UTC by GregJMitchell

### Description
Implements Google OAuth
Adds current_user to app
Adds authorization to controllers
Updates tests to stub current user
### Closes issue(s) #12 

### Testing

### Screenshots

### Changes include
- [ ] Bugfix (non-breaking change that solves an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (change that is not backwards-compatible and/or changes current functionality)

### Checklist
- [ ] I have written tests for this code (happy & sad)
- [ ] I have updated the Readme
- [ ] I ran rubocop and fixed issues
- [ ] I ran full test suite - all tests passing

### Other comments

2021-01-12 16:19 UTC, evilaspaas1 approved these changes

2021-01-12 16:38 UTC, helloeduardo approved these changes
Thanks for all of this work! So excited to have oauth working :)

2021-01-12 16:38 UTC, helloeduardo commented on app/controllers/sessions_controller.rb
> +      client_secret: ENV['GOOGLE_CLIENT_SECRET'],
I think Phil mentioned he would take these out as they are unnecessary in our morning oauth session

2021-01-12 16:38 UTC, helloeduardo commented on config/initializers/omniauth.rb
> +end
Thanks for working out this oauth! 🥇

2021-01-12 16:38 UTC, helloeduardo commented on spec/features/dashboard_spec.rb
> +    it 'If I am not logged in, I am taken to the homepage' do
Great sad path testing here to redirect to the home

2021-01-12 17:15 UTC, evilaspaas1 requested changes
We are working on this at the moment do not merge yet. we are making changes based on multiple API calls vs just the one big one

2021-01-13 00:29 UTC, evilaspaas1 approved these changes
Changes have been made can be merged

2021-01-13 00:30 UTC, merged